Monorepo packages init
siberiacancode/webcam pull request #3
Opened 2024-03-24 01:57 UTC by michael-mir

2024-03-24 05:48 UTC, debabin requested changes

2024-03-24 05:48 UTC, debabin commented on README.md
> +# 📸 Webcam Tools
Webcam просто

2024-03-24 05:48 UTC, debabin commented on README.md
> +For details of supported versions and contact details for reporting security issues, please refer to the [security policy](SECURITY.md).
Я думаю лучше сделать по аналогии с другими нашими доками, гугл рекапча за основу 🦉 Philosophy и features

2024-03-24 05:48 UTC, debabin commented on packages/core/README.md
> +# 📸 Webcam Core
Опять же добавить философию + фичи

2024-03-24 05:48 UTC, debabin commented on packages/core/rollup.config.js
> +});
тут можно сделать просто 

import { generateRollupConfig } from '@siberiacancode/builder';

import pkg from './package.json';

export default generateRollupConfig({ pkg });

2024-03-24 05:48 UTC, debabin commented on packages/core/src/helpers/constraints/getVideoTrackConstraints.ts
> -export type CameraResolutionMode = keyof ConstrainULongRange;
Почему отказался ?

2024-03-24 05:48 UTC, debabin commented on packages/core/README.md
> +- `cameraResolutionMode?` {keyof ConstrainULongRange} - Video track resolution mode
ConstrainULongRange тут старая история

2024-03-24 05:48 UTC, debabin commented on packages/core/src/helpers/stream/canGetUserMedia.ts
> -// In mobile browser work only for https://
это в итоге точно надо удалить ?

2024-03-24 05:48 UTC, debabin commented on packages/core/tsconfig.json
> +  "include": ["declarations.d.ts", "**/*.ts", "../react/src/utils/helpers/animationFrame.ts"],
это точно не так должно быть мне кажется ../react/src/utils/helpers/animationFrame.ts

2024-03-24 05:48 UTC, debabin commented on packages/react/src/components/Webcam/helpers/getWebcamSnapshot.ts
>  export const getWebcamSnapshot = (
я бы вынес это в кор, ведь это можно использовать и вне react

2024-03-24 05:48 UTC, debabin commented on packages/react/src/index.ts
> +} from '@webcam/core';
чот тут странное с sort импортов

2024-03-25 16:59 UTC, michael-mir commented on packages/react/src/index.ts
> +} from '@webcam/core';
Там для шаблона группы нужно внести одно исправление, которое есть в первоисточнике

2024-03-25 17:01 UTC, michael-mir commented on packages/core/rollup.config.js
> +});
Если избавляться от чего-то кроме preset'ов, то при таком раскладе у нас babel хелперы будут складываться в bundle

2024-03-25 17:15 UTC, michael-mir commented on packages/react/src/index.ts
> +} from '@webcam/core';
А, мы не настраивали группы для сортировки экспортов :3

2024-04-01 03:53 UTC, debabin requested changes

2024-04-01 03:53 UTC, debabin commented on README.md
> +For details of supported versions and contact details for reporting security issues, please refer to the [security policy](SECURITY.md).
я бы все таки убрал данную инфу, она и так дублируется много где

2024-04-01 03:53 UTC, debabin commented on packages/core/README.md
> +## 🌌 Installation
Я понял, когда ты говорил про emoji, но думаю тут реально перебор для каждого тайтла такое я бы все таки убрал и сделал так как в других пакетах, а то перебор

2024-04-01 03:53 UTC, debabin commented on packages/core/package.json
> +  },
тут названия надо изменить сразу на новое

2024-04-01 03:53 UTC, debabin commented on packages/core/rollup.config.js
> +      babelHelpers: 'runtime'
А мы не должны тут удалить ?

2024-04-01 03:53 UTC, debabin commented on packages/react/rollup.config.js
>        babelHelpers: 'runtime'
тут тоже удалить

2024-04-01 03:53 UTC, debabin commented on packages/react/rollup.config.js
>  import { generateRollupConfig } from '@siberiacancode/builder';
файл нужно вообще в ts сделать просто

2024-04-02 16:54 UTC, michael-mir commented on packages/core/rollup.config.js
> +      babelHelpers: 'runtime'
https://github.com/siberiacancode/react-webcam-ultimate/pull/3#discussion_r1537925907

2024-04-02 16:54 UTC, michael-mir commented on packages/react/rollup.config.js
>        babelHelpers: 'runtime'
https://github.com/siberiacancode/react-webcam-ultimate/pull/3#discussion_r1537925907

2024-04-02 17:10 UTC, debabin commented on packages/core/rollup.config.js
> +});
так это нормально совершено, у тебя не будет просто в nodejs просто так babel их надо положит ьв бандл

2024-04-05 17:46 UTC, merged